export const initialSubscriptions = [
  {
    id: 1,
    name: "Netflix",
    amount: 15,
    currency: "USD",
    category: "Entretenimiento",
    frequency: "Mensual",
    billingDay: 3,
    isActive: true,
  },
  {
    id: 2,
    name: "Spotify",
    amount: 12,
    currency: "USD",
    category: "Entretenimiento",
    frequency: "Mensual",
    billingDay: 5,
    isActive: true,
  },
  {
    id: 3,
    name: "Adobe Creative Cloud",
    amount: 59,
    currency: "USD",
    category: "Productividad",
    frequency: "Mensual",
    billingDay: 8,
    isActive: true,
  },
  {
    id: 4,
    name: "Gym Pro",
    amount: 49,
    currency: "EUR",
    category: "Salud",
    frequency: "Mensual",
    billingDay: 12,
    isActive: true,
  },
  {
    id: 5,
    name: "Internet",
    amount: 65,
    currency: "USD",
    category: "Hogar",
    frequency: "Mensual",
    billingDay: 15,
    isActive: true,
  },
  {
    id: 6,
    name: "Notion",
    amount: 10,
    currency: "USD",
    category: "Productividad",
    frequency: "Mensual",
    billingDay: 18,
    isActive: true,
  },
  {
    id: 7,
    name: "AWS",
    amount: 42,
    currency: "USD",
    category: "Tecnología",
    frequency: "Mensual",
    billingDay: 24,
    isActive: true,
  },
];